version: 0.1
os: linux
files:
  - source: /
    destination: /home/ec2-user/car-rental
hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 40
      runas: ec2-user
  BeforeInstall:
    - location: scripts/prepare_application.sh
      timeout: 40
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 40
      runas: ec2-user
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 40
      runas: ec2-user