version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/car-rental
hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 40
      runas: root
  BeforeInstall:
    - location: scripts/clean.sh
      timeout: 40
      runas: root
  AfterInstall:
    - location: scripts/prepare_application.sh
      timeout: 40
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 40
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 40
      runas: root