spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car_rental?createDatabaseIfNotExist=true
    username: ${bd.user}
    password: ${bd.password}
    driver-class: mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  cloud:
    aws:
      secretsmanager:
        endpoint: http://localhost:4566
  config:
    import: aws-secretsmanager:/secret/car-rental_default