server:
  port: 8081
  host: http://localhost:4200
spring:
  datasource:
    driver-class: mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email.user}
    password: ${email.key}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org:
      springframework:
        security: ERROR
keycloak:
  url: http://localhost:8080/
  realm: car-rental-security
  admin-user: ${keycloak.admin.user}
  admin-password: ${keycloak.admin.password}
  admin-client-id: admin-cli
  realm-admin: master

email:
  url:
    create-password: ${server.host}/login/create-password?user={userId}&code={codeId}
    reset-password: ${server.host}/login/reset-password?user={userId}&code={codeId}&credential={credentialId}