server:
  port: 8081
spring:
  datasource:
    driver-class: mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email.user}
    password: ${email.key}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
keycloak:
  url: http://localhost:8080/
  realm: car-rental-security
  admin-user: ${keycloak.admin.user}
  admin-password: ${keycloak.admin.password}
  admin-client-id: admin-cli
  realm-admin: master