server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car_rental?createDatabaseIfNotExist=true
    username: ${bd.user}
    password: ${bd.password}
    driver-class: mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  cloud:
    aws:
      secretsmanager:
        endpoint: http://localhost:4566
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/${keycloak.app.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email.user}
    password: ${email.key}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  config:
    import: aws-secretsmanager:/secret/car-rental_default

keycloak:
  url: http://localhost:8080/
  realm: ${keycloak.app.realm}
  admin-user: ${keycloak.admin.user}
  admin-password: ${keycloak.admin.password}
  admin-client-id: ${keycloak.admin.client}
  realm-admin: ${keycloak.admin.realm}